# Generated by Django 2.2.12 on 2022-02-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('project_pictures', models.ImageField(upload_to='')),
                ('total_target', models.ImageField(upload_to='')),
                ('tags', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('project_show', models.BooleanField(default=0)),
            ],
        ),
    ]
