# Generated by Django 4.0.2 on 2022-02-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fundproject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='details',
            field=models.TextField(),
        ),
    ]
