# Generated by Django 3.2.10 on 2022-02-18 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundproject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_id',
        ),
    ]
