# Generated by Django 3.2.10 on 2022-02-18 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fundproject', '0002_remove_comment_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user_id',
        ),
    ]
